============================================================
-- Healthcare Claims Data Platform
-- Snowflake Setup Script
============================================================

-- Use admin role for setup
USE ROLE ACCOUNTADMIN;

-- Create warehouse
CREATE WAREHOUSE IF NOT EXISTS HEALTHCARE_WH
WITH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

-- Create database
CREATE DATABASE IF NOT EXISTS HEALTHCARE_CLAIMS_DB;

-- Create schema
CREATE SCHEMA IF NOT EXISTS HEALTHCARE_CLAIMS_DB.GOLD;

-- Set context
USE WAREHOUSE HEALTHCARE_WH;
USE DATABASE HEALTHCARE_CLAIMS_DB;
USE SCHEMA GOLD;

-- ============================================================
-- Create Gold Tables
-- ============================================================

CREATE OR REPLACE TABLE DIM_PATIENT (
    PATIENT_ID STRING,
    FIRST_NAME STRING,
    LAST_NAME STRING,
    DOB DATE,
    GENDER STRING,
    STATE STRING,
    GOLD_PROCESSED_TIMESTAMP TIMESTAMP
);

CREATE OR REPLACE TABLE DIM_PROVIDER (
    PROVIDER_ID STRING,
    PROVIDER_NAME STRING,
    SPECIALTY STRING,
    STATE STRING,
    NPI STRING,
    GOLD_PROCESSED_TIMESTAMP TIMESTAMP
);

CREATE OR REPLACE TABLE FACT_CLAIMS (
    CLAIM_ID STRING,
    PATIENT_ID STRING,
    PROVIDER_ID STRING,
    CLAIM_DATE DATE,
    DIAGNOSIS_CODE STRING,
    PROCEDURE_CODE STRING,
    CLAIM_AMOUNT NUMBER(12,2),
    STATUS STRING,
    PATIENT_STATE STRING,
    PATIENT_GENDER STRING,
    PROVIDER_NAME STRING,
    SPECIALTY STRING,
    PROVIDER_STATE STRING,
    TOTAL_PAID_AMOUNT NUMBER(12,2),
    PAYMENT_COUNT NUMBER,
    CLAIM_BALANCE_AMOUNT NUMBER(12,2),
    IS_DENIED NUMBER,
    IS_APPROVED NUMBER,
    GOLD_PROCESSED_TIMESTAMP TIMESTAMP
);

CREATE OR REPLACE TABLE CLAIM_SUMMARY_MONTHLY (
    CLAIM_YEAR NUMBER,
    CLAIM_MONTH NUMBER,
    TOTAL_CLAIMS NUMBER,
    TOTAL_CLAIM_AMOUNT NUMBER(12,2),
    TOTAL_PAID_AMOUNT NUMBER(12,2),
    AVG_CLAIM_AMOUNT NUMBER(12,2),
    DENIED_CLAIMS NUMBER,
    APPROVED_CLAIMS NUMBER,
    DENIAL_RATE_PERCENT NUMBER(6,2),
    APPROVAL_RATE_PERCENT NUMBER(6,2),
    GOLD_PROCESSED_TIMESTAMP TIMESTAMP
);

CREATE OR REPLACE TABLE PROVIDER_PERFORMANCE_SUMMARY (
    PROVIDER_ID STRING,
    PROVIDER_NAME STRING,
    SPECIALTY STRING,
    PROVIDER_STATE STRING,
    TOTAL_CLAIMS NUMBER,
    TOTAL_CLAIM_AMOUNT NUMBER(12,2),
    TOTAL_PAID_AMOUNT NUMBER(12,2),
    AVG_CLAIM_AMOUNT NUMBER(12,2),
    DENIED_CLAIMS NUMBER,
    APPROVED_CLAIMS NUMBER,
    DENIAL_RATE_PERCENT NUMBER(6,2),
    APPROVAL_RATE_PERCENT NUMBER(6,2),
    GOLD_PROCESSED_TIMESTAMP TIMESTAMP
);

CREATE OR REPLACE TABLE DENIAL_SUMMARY (
    DIAGNOSIS_CODE STRING,
    SPECIALTY STRING,
    PROVIDER_STATE STRING,
    DENIED_CLAIMS NUMBER,
    DENIED_CLAIM_AMOUNT NUMBER(12,2),
    AVG_DENIED_CLAIM_AMOUNT NUMBER(12,2),
    GOLD_PROCESSED_TIMESTAMP TIMESTAMP
);

CREATE OR REPLACE TABLE PAYMENT_SUMMARY (
    STATUS STRING,
    TOTAL_CLAIMS NUMBER,
    TOTAL_CLAIM_AMOUNT NUMBER(12,2),
    TOTAL_PAID_AMOUNT NUMBER(12,2),
    AVG_PAID_AMOUNT NUMBER(12,2),
    TOTAL_BALANCE_AMOUNT NUMBER(12,2),
    PAYMENT_RATE_PERCENT NUMBER(6,2),
    GOLD_PROCESSED_TIMESTAMP TIMESTAMP
);